GREASE_REPOSITORY_REVISION=3af742a82a96983f92e13155f9b4787940c32d8e
GREASE_RELEASE_TAG=netbsd-9.3-amd64-3af742a82a96
GREASE_ARCHIVE_NAME=grease-netbsd-9.3-amd64.tar.gz
GREASE_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-9.3-amd64-3af742a82a96/grease-netbsd-9.3-amd64.tar.gz
GREASE_SHA256_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-9.3-amd64-3af742a82a96/grease-netbsd-9.3-amd64.tar.gz.sha256
GREASE_SHA256=b70d3d222458512dbf67424a33fe463ae79b2c61dc41915424f810cc66d4f8ea
GREASE_TARGET_SYSTEM=NetBSD
GREASE_TARGET_RELEASE=9.3
GREASE_TARGET_MACHINE=amd64
