GREASE_REPOSITORY_REVISION=1c7f2c8bc691857857ef2beea65db6e3714ec518
GREASE_RELEASE_TAG=netbsd-11-amd64-1c7f2c8bc691
GREASE_ARCHIVE_NAME=grease-netbsd-11-amd64.tar.gz
GREASE_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-11-amd64-1c7f2c8bc691/grease-netbsd-11-amd64.tar.gz
GREASE_SHA256_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-11-amd64-1c7f2c8bc691/grease-netbsd-11-amd64.tar.gz.sha256
