GREASE_REPOSITORY_REVISION=60641ddd99844655c0788f790cd3a8a14c7166fd
GREASE_RELEASE_TAG=netbsd-9.3-amd64-60641ddd9984
GREASE_ARCHIVE_NAME=grease-netbsd-9.3-amd64.tar.gz
GREASE_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-9.3-amd64-60641ddd9984/grease-netbsd-9.3-amd64.tar.gz
GREASE_SHA256_URL=https://github.com/dilapidated-shed/grease/releases/download/netbsd-9.3-amd64-60641ddd9984/grease-netbsd-9.3-amd64.tar.gz.sha256
GREASE_SHA256=a7f5e35feebd1a222e2ae724bbbf4a2c1fe28c5683ac3aa6561ed770a9bb3136
GREASE_TARGET_SYSTEM=NetBSD
GREASE_TARGET_RELEASE=9.3
GREASE_TARGET_MACHINE=amd64
